### PR TITLE
User can see List of restaurants

### PR DESCRIPTION
**Pull request by nirav-improwised**
Obtained data by API call in `pages/index.vue` then passed that data to `components/List.vue` and displayed data using cards.

image

### CODE REVIEW

**Comment by monikagorkhiya** [comment]
Need to improve design and  show some specific details on main card
image

**Comment by nirav-improwised** [comment]
Improved card design. Removed borders, added ratings and changed card-layout.
Also applied spacing (gutter) between cards.

image

**Comment by nirav-improwised** [comment]
Added shadow to card, to differentiate cards properly.

Don't merge it yet, I am adding card data.

image

**Comment by nirav-improwised** [comment]
Added 'Delivering Now' data to card.
image

**Review by monikagorkhiya — APPROVED** [review]

**Pull request merged**
