### PR TITLE
Component-Functionality-SearchPanel

### PR DESCRIPTION
**Pull request by nirav-improwised**
Added JS code to get cities, made dropdown for location searchbox

### CODE REVIEW

**Comment by nirav-improwised** [comment]
**Earlier** I have **implemented** Search functionality by **using emits** and filtering data in index.vue, after talking with tapanbhai I have **now** **implemented** the Search functionality **by reading query string**.
And also this time I have **done filtering** of Data **in "List.vue"** file, to keep the index.vue file clean.

**Comment by monikagorkhiya** [comment]
Trash.txt?

**Comment by nirav-improwised** [comment]
I was facing some issues yeaterday and was trying different approaches, so I took back up of what was earlier working in trash.txt

I forgot to remove it.

**Comment by nirav-improwised** [comment]
Reduced space between navbar and Search Panel, also made custom class to give top padding to the Search Panel heading "Discover Best Restaurants Delivering Near You".

image

**Review by monikagorkhiya — APPROVED** [review]

**Pull request merged**
